apiVersion: v1
kind: Service
metadata:
  labels:
    app: portal
  name: portal-web-service
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: portal
    component: web-server
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: portal
  name: portal-web-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: portal
        component: web-server
    spec:
      containers:
      - name: portal
        # Make sure to specify the right image version here!
        image: gcr.io/traansmission-1bdc/portal:v3.0.6-sandbox
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 50m
            memory: "128Mi"